name: Release
on:
  pull_request:
    types:
      - closed
jobs:
  tag:
    name: Tag
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semver Tag
        uses: K-Phoen/semver-release-action@v1.3.2
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}